version: "3"
services: 
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports: 
            - 3000:3000
        networks: 
            - mern-network
        volumes: 
            - ./client/src:/usr/app/src
            - ./client/public:/usr/app/public
        depends_on: 
            - server
        environment: 
            - REACT_APP_SERVER=http://localhost:5000
            - CHOKIDAR_USEPOLLING=true
        command: npm run dev
        # stdin_open and tty will keep the client container live and open to requests after starting up (without it, client will exit immediately)
        stdin_open: true
        tty: true

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        networks: 
            - mern-network
        volumes: 
            - ./server/src:/usr/app/src
        depends_on: 
            - db
        environment: 
            - MONGO_URL=mongodb://db:27017/soccerDB
            - CLIENT=http://localhost:3000
        command: npm run dev
    
    db:
        image: mongo:4.0-xenial
        ports:
            - 27017:27017
        networks: 
            - mern-network
        volumes: 
            - mongo-data:/data/db
        
networks:
    mern-network:
        driver: bridge

volumes: 
    mongo-data:
        driver: local